### ISSUE TITLE
make: Nothing to be done for 'all'.

### ISSUE THREAD

**Issue by rbraddev** [fuzzyTew/wslunpindir#1]
When I run make inside the wslunpindir folder I get:
`make: Nothing to be done for 'all'.`

I have installed syscall_intercept.

**Comment by xloem** [comment]
This is because I've already called 'make' for you, if you'd like.  When you pull the source down, `interceptrename.so` is already built.

If you would like to rebuild it without changing the source, you can update the timestamp of the sourcefile so make thinks there is a need to rebuild:
```
touch interceptrename.c
make
```
I'll update the readme.

**Comment by rbraddev** [comment]
So do I copy the interceptrename.so in the project directory, then run:
`LD_PRELOAD=interceptrename.so npm install`

When I do that, I get this error:
`ERROR: ld.so: object 'interceptrename.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

**Comment by rbraddev** [comment]
I think I have figured it out. Thank you.

**Comment by xloem** [comment]
I updated the readme to describe installing the .so files in /usr/lib, and to make fully.  dependency lib is now in the git too, for ease.
thanks for letting me know about this hiccup.

**Comment by fuzzyTew** [comment]
I updated the readme to describe installing the .so files in /usr/lib, and to make fully. dependency lib is now in the git too, for ease.
thanks for letting me know about this hiccup.
